# Generated by Django 4.1.7 on 2023-02-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rank',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='Рейтинг'),
        ),
    ]
