# Generated by Django 4.1.7 on 2023-02-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_vote_book_rating_delete_rating_vote_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Нормально'), ('2', 'Плохо'), ('1', 'Ужасно')], null=True, verbose_name='Рейтинг'),
        ),
    ]
